apiVersion: v1
kind: Service
metadata:
  name: platformnpservice-srv
spec:
  type: NodePort
  selector:
    app: microservice1
  ports:
    - name: microservice1
      protocol: TCP
      port: 80
      targetPort: 80
